#%RAML 0.8
title: RMS4CSW API
baseUri: http://computerstudienwerkstatt.de/api/{version}
version: v1

mediaType: application/json
protocols: HTTPS
uses:
  Devices: !include devices/devices.raml

# traits:
#   secured: !include access/token.raml

/devices:
  # is: secured
  get:
    queryParameters:
      class:
        description: Filter by device class id
        type: string
    responses:
      200:
        body:
          application/json:
